### ISSUE TITLE
Textarea values not updating correctly

### ISSUE THREAD

**Issue by elliotdickison** [elm-lang/virtual-dom#115]
### Situation

I have an app with a list of textareas. The user can add new textareas, remove existing textareas, and update the value of each textarea.

### Problem

If the user removes a textarea then the values of the other textareas move to the textarea at the same index in the DOM instead of sticking to their original textarea elements. For example, given the list of (textarea, value) `[ (a, 1), (b, 2), (c, 3), (d, 4), (e, 5) ]`, if the user removes textarea `c` the final list becomes `[ (a, 1), (b, 2), (d, 3), (e, 4) ]`. However, if you inspect the DOM the correct value is shown as a child of each textarea element - `[ (a, 1), (b, 2), (d, 4), (e, 5) ]`. It's a bit hard to describe here, the reduced test case below should make it clearer.

NOTE: This only occurs if the user has changed the value of the textarea. If the value remains unchanged from it's first render to the DOM then it will stick to the correct element even if the element's index in the DOM changes.

### Reduced test case

Tested in Chrome 61.0.3163.79 on macOS 10.12.6: https://ellie-app.com/4j3v8zjC37Ha1/0

**Comment by zwilias** [comment]
The text content for a `textarea` is only used as the initial value when first appended to the document. Further changes to the content don't update the value. This is a DOM limitation, essentially.

Realistically, you have two options:
- using `Html.Attributes.value` rather than appending a `text` element like so: https://ellie-app.com/4jj5KrD8CVwa1/0
- using `Html.Keyed` to prevent unwanted DOM-node reuse: https://ellie-app.com/4jj5KrD8CVwa1/1

I think the first option is the better one.

**Comment by elliotdickison** [comment]
@zwilias I did not realize textarea could take a value attribute, or that `Html.Keyed` existed. Thank you!
