### ISSUE TITLE
video tracks are duplicated after re-rendering

### ISSUE THREAD

**Issue by rnons** [elm-lang/virtual-dom#116]
A reproducible repo: https://github.com/rnons/elm-video-track-issue

![image](https://user-images.githubusercontent.com/1082650/30814808-2a138678-a24c-11e7-88ee-e361d95e33d8.png)

There is a video tag and two buttons.
The issue is when I click button to change subtitle languages, old track is still there.

**Comment by zwilias** [comment]
@rnons it seems that if you update the `src` of a `track` element (which is what Elm does here, as it is the minimal change required), the browser interprets that as _adding_ a subtitle track.

The easiest fix here, is to force Elm to remove the old `track` element (which removes the subtitle track entirely) and adding a fresh `track` element. In order to do so, you'll want to use [`Html.Keyed`](package.elm-lang.org/packages/elm-lang/html/2.0.0/Html-Keyed) like so:

```elm
import Html.Keyed

view model =
    div []
        [ Keyed.node "video"
            [ controls True ]
            [ ( "video", source [ src "https://download.ted.com/talks/RandallMunroe_2014-320k.mp4" ] [] )
            , ( model.selected, track [ src model.selected, default True ] [] )
            ]
        , div []
            [ button [ onClick (SelectLang "en.vtt") ] [ text "en" ]
            , button [ onClick (SelectLang "zh-cn.vtt") ] [ text "zh-cn" ]
            ]
        ]
```

**Comment by rnons** [comment]
@zwilias works great, I didn't know about `Html.Keyed` before. Thank you very much.
