### ISSUE TITLE
applyFacts error with date type input and IE

### ISSUE THREAD

**Issue by bigardone** [elm-lang/virtual-dom#72]
Hi!
I'm using **Elm 0.18** in a new project I'm working on, and while testing it on **IE11** and **IE10**, the application doesn't run due to a javascript error. I'm not really sure if this is the correct repository where to place this issue, but it's in the `applyFacts` function. To test it I'm using a multi-browser testing service, so I'm only able to take screenshots, but I hope it helps.
This is the error it throws:

![captura de pantalla 2016-12-15 a las 17 44 57](https://cloud.githubusercontent.com/assets/1090272/21233503/9c4ed9a0-c2ef-11e6-9472-e1bcf8626c8f.png)

![captura de pantalla 2016-12-15 a las 17 48 01](https://cloud.githubusercontent.com/assets/1090272/21233490/908886ca-c2ef-11e6-83f1-3d14c6f3f143.png)

It works on any other regular browser, so I guess it might be something related to **IE** and `<input type="date" />` that I'm using. Does it make any sense?
Thanks in advance :)

**Comment by jfornoff** [comment]
Encountered this as well, IE 11.0.09600, only with input[type="date"]

**Comment by mrozbarry** [comment]
I can confirm, and there is a reasonable fix.

In IE 11, if I do:

```
var e = document.createElement("input")
e.type = "date"
```

The browser throws an exception, but if I set it using `element.setAttribute`, it does not throw an exception, but does gracefully fallback to `type="text"`:

```
var e = document.createElement("input")
e.setAttribute("type", "date")
```

Is there a reason that virtual dom would use `element[key] = value` over `element.setAttribute(key, value)`?

**Comment by peteygao** [comment]
This also plagues IE9, when using `type_ "range"`. I imagine this issue occur whenever a `type` that's not supported by the IE version in question is set (`range` works in IE10, as an example, and thus will not throw this error for my particular use-case).

Thanks for that tip @mrozbarry, I'm going to make that patch locally to see if that resolves the problem for my use-case and report back.

**Comment by peteygao** [comment]
Seems like there's [a lot of issues](http://quirksmode.org/dom/core/#attributes) with using `setAttribute`, chief among them the fact that you _must_ use `getAttribute` to fetch them (which breaks the current VirtualDom implementation--I made the patch that @mrozbarry mentioned by swapping `domNode[key] = value;` with `domNode.setAttribute(key, value);` and the entire page broke even in non-IE browsers).

It [also seems to be the recommended practice](stackoverflow.com/questions/3919291/when-to-use-setattribute-vs-attribute-in-javascript) to set/retrieve _properties_ (e.g. `Element.propertyName = value`) rather than interacting with HTML/DOM-level _attributes_ (which is what the `setAttribute`/`getAttribute` setter/getter perform).

But here's the **real kicker**: the `type` attribute is READONLY in <= IE9 according to a third party [IE bug tracker bug #237](http://webbugtrack.blogspot.com/2007/09/bug-237-type-is-readonly-attribute-in.html). According to the bug description:
>In a DOM compliant browser, this is a piece of cake. However in IE ([msdn article](https://msdn.microsoft.com/en-us/library/ms534700.aspx)), the type attribute is read-only... except for a small window of time before you add an element to the DOM (e.g. if you are using createElement() )
>
>**Known Workarounds:** None. If you copy all the information for a given node, into JS variables, then remove the existing element, and create a brand new one in its place, then you are set.

And low and behold, indeed the [MSDN article](https://msdn.microsoft.com/en-us/library/ms534700.aspx) mentions that the `type` attribute is write-once only:
>The **type** property is read/write-once, but only when an input element is created with the createElement method and before it is added to the document.

Ugh 🤦‍...

**Comment by evancz** [comment]
Tracking in #106 which is for any `type_` issues.

Please continue discussion here if there is more information to share. The point of the meta issue is to do some organizing and editorializing that makes it easier to make progress on this sort of thing.
