### ISSUE TITLE
Write tests automatically (feature request)

### ISSUE THREAD

**Issue by willnwhite** [elm-lang/virtual-dom#75]
The debugger has the model, msg and the new model. So if you tell it that the new model is indeed the expected return value from `update msg model`, it can write that test for you. I've gone into more detail with an example here: https://github.com/elm-lang/elm-make/issues/138#issuecomment-270371165

**Comment by peteygao** [comment]
This is an amazing concept and the kind of _out of the box_ thinking that I love when I see it occur in the Elm community!

Conceptually, it's a tool for record an integration test that is at the data model level instead of the UI level (and thus sidestepping certain bugs like when buttons/inputs change class/id/positions).

Although perhaps the benefit is somewhat short lived as the generated test would have to be hand pruned if the message type changes (which I imagine would happen quite often under development). But it does make complex interactions easily encodable.

Still, absolutely worth exploring, though it might be a conversation best taken to the [Elm Discussion Group](https://groups.google.com/forum/?fromgroups#!forum/elm-discuss) since the Issues queue isn't where discussions are promoted to occur as per the [contribution checklist](https://github.com/process-bot/contribution-checklist/blob/master/participation.md).

**Comment by willnwhite** [comment]
Thanks Peter. I've taken the discussion to elm-discuss: https://groups.google.com/forum/#!topic/elm-discuss/QwxCP-GXY7U

**Comment by evancz** [comment]
Yeah, this is something that seems like a good direction to go with this kind of tool. Want to keep issues for tracking bugs though, so closing.
