### ISSUE TITLE
"too much recursion" error in Firefox when debugging is enabled

### ISSUE THREAD

**Issue by tekul** [elm-lang/virtual-dom#80]
When I run the test case [provided in this repo](https://github.com/tekul/reactor-crash) I get the error:

```
too much recursion[Learn More]  Main.elm:1162:2
    compare http://localhost:8000/_compile/src/Main.elm:1162:2
    A2 http://localhost:8000/_compile/src/Main.elm:92:7
    _elm_lang$core$Dict$get< http://localhost:8000/_compile/src/Main.elm:4589:16
    A2 http://localhost:8000/_compile/src/Main.elm:92:7
    _elm_lang$virtual_dom$VirtualDom_Expando$mergeDictHelp< http://localhost:8000/_compile/src/Main.elm:8948:14
    wrapper/</< http://localhost:8000/_compile/src/Main.elm:16:54
    A2 http://localhost:8000/_compile/src/Main.elm:93:7
    _elm_lang$core$Dict$map< http://localhost:8000/_compile/src/Main.elm:5066:5
    A2 http://localhost:8000/_compile/src/Main.elm:92:7
    _elm_lang$virtual_dom$VirtualDom_Expando$mergeHelp< http://localhost:8000/_compile/src/Main.elm:8922:9
    A2 http://localhost:8000/_compile/src/Main.elm:92:7
    _elm_lang$virtual_dom$VirtualDom_Expando$mergeListHelp< http://localhost:8000/_compile/src/Main.elm:8966:10
    A2 http://localhost:8000/_compile/src/Main.elm:92:7
    _elm_lang$virtual_dom$VirtualDom_Expando$mergeListHelp< http://localhost:8000/_compile/src/Main.elm:8967:10
    A2 http://localhost:8000/_compile/src/Main.elm:92:7
    _elm_lang$virtual_dom$VirtualDom_Expando$mergeListHelp< http://localhost:8000/_compile/src/Main.elm:8967:10
    A2 http://localhost:8000/_compile/src/Main.elm:92:7
```

I'm using Elm 0.18 on Arch Linux with Firefox 50.1.0.

At first I thought it was something to do with the reactor (I'm new to elm), but it only appears when debugging is enabled and it seems the code is part of this module - I was able to get rid of the problem by replacing  `VirtualDom.Expando.merge` with

```
merge : a -> Expando -> Expando
merge value _ =
   (Native.Debug.init value)
```

thus skipping the recursive code in question. Everything then works as expected.

**Comment by hans-helmut** [comment]
I experienced a similar issue when using elm-pouchdb. I am new to ELM, my assumption is, that printing recursive data-structures, as created by pouchdb, causes a infinitive loop. I could fix it by limiting the recursion the hard way:

elm-stuff/packages/elm-lang/virtual-dom/2.0.4/src/Native/Debug.js

@@ -108,7 +108,7 @@
 }
 
 
-function init(value)
+function init(value, r=0)
 {
 	var type = typeof value;
 
@@ -223,9 +223,11 @@
 	if (type === 'object')
 	{
 		var dict = _elm_lang$core$Dict$empty;
+		if (r < 10) {
 		for (var i in value)
 		{
-			dict = A3(_elm_lang$core$Dict$insert, i, init(value[i]), dict);
+			dict = A3(_elm_lang$core$Dict$insert, i, init(value[i], r+1), dict);
+		}
 		}
 		return { ctor: 'Record', _0: true, _1: dict };
 	}

**Comment by ianmackenzie** [comment]
I've also run into this issue when having large lists in my model - depending on the size of the list in question it can manifest as either a stack overflow from too much recursion, or just a performance hit from the debugger traversing the list after every update. I've made [a slightly simpler SSCCE](https://github.com/ianmackenzie/elm-debugger-performance-sscce) where the problem manifests as a slowdown instead of a crash.

Evan, you [mentioned](https://www.reddit.com/r/elm/comments/628efv/avoiding_slowdown_when_using_the_debugger/dfkq6ti/) lazy evaluation in the debugger as a potential solution, but could a simpler (perhaps temporary) fix be to have the debugger basically do a `List.take 100` on any list it finds, then just display `...` if the list is longer than that? I think it's reasonable that the debugger would only show you the first 100 items in any given list.

If it helps anyone, I [posted a workaround](https://www.reddit.com/r/elm/comments/628efv/avoiding_slowdown_when_using_the_debugger/) you can use for this issue - basically just 'hide' the problematic value inside a function, since the debugger will not attempt to introspect functions.

**Comment by evancz** [comment]
Tracking in #98. Thanks for the report!
