### ISSUE TITLE
Debugger not taking full advantage of width of window [minor, Expando]

### ISSUE THREAD

**Issue by RJWoodhead** [elm-lang/virtual-dom#83]
It would be nice if the debugger took full advantage of the width of the debug window when displaying unexpanded records.

Currently, Expando truncates fields when the record is unexpanded, which does not take advantage of unused space in the debugger window (especially if it is enlarged)

An alternate presentation would be to not truncate the fields but use white-space: nowrap in the div,  which would use the entire width but restrict the record to a single line. If the record is too big to fully display the user could either scroll the window horizontally or expand the record.

**Comment by evancz** [comment]
Tracking in #98. Thanks for the report!

Computing dynamic layouts may be quite expensive when it comes to code. A lot of the browser stuff is fine for text. Check out how these things work in Chrome Dev Tools for example. Last I checked, it did not seem to be based on width. This could be because during debugging, *regular* and *recognizable* structure may be more valuable than other considerations.
